"""
UnionFind generated by WenXinYiYan
"""

class UnionFind:  
    def __init__(self, n):  
        # 初始化每个元素的父节点为其自身，表示每个元素最初都是一个独立的集合  
        self.parent = list(range(n))  
  
    def find(self, x):  
        # 查找元素x所属的集合，即找到x的根节点  
        if self.parent[x] != x:  
            self.parent[x] = self.find(self.parent[x])  # 路径压缩，优化后续查找操作  
        return self.parent[x]  
  
    def union(self, x, y):  
        # 合并元素x和y所在的集合  
        rootX = self.find(x)  
        rootY = self.find(y)  
        if rootX != rootY:  
            self.parent[rootX] = rootY  # 将一个集合的根节点设置为另一个集合的根节点的子节点，完成合并  
  
    def connected(self, x, y):  
        # 查询元素x和y是否属于同一集合  
        return self.find(x) == self.find(y)